version: "3.9"

services:
  mysql:
    image: "mysql:8.0.28"
    restart: always
    environment:
      TZ: ${TZ}
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - "mysql-data:/var/lib/mysql"
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD"
      interval: 5s
      timeout: 3s
      retries: 10

  php:
    build:
      context: ./php
    restart: always
    volumes:
      - ./php/app:/var/www/html/
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      SUBSCRIPTION_BASE_URL: ${SUBSCRIPTION_BASE_URL}
    ports:
      - '127.0.0.1:9000:9000'

  tgbot:
    build:
      context: ./bot
    restart: always
    environment:
      SUBSCRIPTION_SERVER_URL: ${SUBSCRIPTION_SERVER_URL}
      SUBSCRIPTIONS_MAX_COUNT: ${SUBSCRIPTIONS_MAX_COUNT}
      BOT_TOKEN: ${BOT_TOKEN}
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - mysql

  webhook:
    build:
      context: ./webhook
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "127.0.0.1:8088:8088"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
